/**
 * Growth illustration pipeline: the client's render -> responsive WebP with alpha.
 *
 *   node tools/growth.mjs
 *
 * Same shape as tools/hero.mjs and for the same reasons — widths derived from the
 * source, a manifest the markup reads so it can never advertise a file that does not
 * exist, and no upscaling. Two things differ:
 *
 *   ALPHA IS LOAD-BEARING. The render is a cutout on transparency and it sits on the
 *   About section's gradient wash, so it cannot be flattened onto a matte. `.webp()`
 *   keeps the alpha channel; do not add `.flatten()` to save bytes.
 *
 *   THE SOURCE IS SMALL. growth.png is 500x500, which is the ceiling here, and the
 *   graphic is sized in CSS so that ceiling is not obviously exceeded on a 2x screen.
 *   If the client ever re-exports it larger, drop the new file in and re-run: the
 *   extra widths below start emitting on their own and the markup follows the
 *   manifest without an edit.
 */

import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const CANDIDATES = ['src/assets/growth-full.png', 'growth.png', 'brand/growth.png'];
const OUT = 'public/art';
const MANIFEST = 'src/data/growth-art.json';
const NAME = 'growth';

/* Widths of the CROPPED subject, not the source canvas. The first two are what the
   current export can honestly fill; the ones above are deliberately left in — they
   cost nothing while the source is small and they are the whole upgrade path if a
   bigger export ever arrives. */
const WIDTHS = [280, 420, 640, 900];

/* Alpha below this is invisible on paper and is treated as margin, not artwork. */
const ALPHA_FLOOR = 8;
/* A few pixels of slack so a faint glow is never clipped by an off-by-one bbox. */
const PAD = 4;

/* Higher than the hero's 72. This is a smooth 3D render with large flat gradients and
   a neon edge — quality shows here at a fraction of the byte cost a photograph pays,
   and banding in the glow is the one artefact that would be obvious. */
const QUALITY = 82;

const src = CANDIDATES.find((f) => existsSync(f));
if (!src) {
  console.error(`no source image found — looked for:\n  ${CANDIDATES.join('\n  ')}`);
  process.exit(1);
}

const meta = await sharp(src).metadata();
if (!meta.hasAlpha) {
  console.warn(`WARNING: ${src} has no alpha channel. The illustration sits on the`);
  console.warn(`About section's wash, so a baked-in white box will be visible.`);
}

await mkdir(OUT, { recursive: true });

/**
 * Crop to the artwork.
 *
 * The 500x500 export is 60% transparent margin — the subject occupies a landscape
 * band across the middle. Shipping the canvas would have cost bytes for nothing and,
 * worse, forced a square hole in the layout with the illustration floating small in
 * the centre of it. Cropping makes the graphic's box the graphic.
 *
 * Done by measuring alpha rather than with sharp's `.trim()`, which decides its
 * threshold from the corner pixel and would silently take the whole canvas the day a
 * render arrives with a faint full-bleed glow.
 */
async function contentBox() {
  const { data, info } = await sharp(src).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  let x0 = info.width, y0 = info.height, x1 = -1, y1 = -1;
  for (let y = 0; y < info.height; y++) {
    for (let x = 0; x < info.width; x++) {
      if (data[(y * info.width + x) * info.channels + 3] <= ALPHA_FLOOR) continue;
      if (x < x0) x0 = x;
      if (x > x1) x1 = x;
      if (y < y0) y0 = y;
      if (y > y1) y1 = y;
    }
  }
  if (x1 < 0) throw new Error(`${src} is fully transparent`);
  const left = Math.max(0, x0 - PAD);
  const top = Math.max(0, y0 - PAD);
  return {
    left,
    top,
    width: Math.min(info.width - left, x1 - x0 + 1 + PAD * 2),
    height: Math.min(info.height - top, y1 - y0 + 1 + PAD * 2),
  };
}

const box = await contentBox();

const report = [];
for (const width of WIDTHS) {
  if (width > box.width) continue; // never upscale — bytes without detail
  const out = `${OUT}/${NAME}-${width}.webp`;
  const buf = await sharp(src)
    .extract(box)
    .resize({ width, withoutEnlargement: true })
    .webp({ quality: QUALITY, effort: 6, alphaQuality: 100 })
    .toBuffer();
  await writeFile(out, buf);
  const m = await sharp(buf).metadata();
  report.push({ out, w: m.width, h: m.height, kb: +(buf.length / 1024).toFixed(1) });
}

if (!report.length) {
  console.error(`artwork is ${box.width}px wide — smaller than the narrowest output`);
  process.exit(1);
}

const largest = report.at(-1);

await mkdir('src/data', { recursive: true });
await writeFile(
  MANIFEST,
  JSON.stringify(
    {
      note: 'generated by tools/growth.mjs — do not edit by hand',
      src: `/${report[0].out.replace(/^public\//, '')}`,
      width: largest.w,
      height: largest.h,
      ratio: +(largest.w / largest.h).toFixed(4),
      sources: report.map((r) => ({ src: `/${r.out.replace(/^public\//, '')}`, w: r.w })),
    },
    null,
    2,
  ) + '\n',
);

console.log(`source     ${src} (${meta.width}x${meta.height}, alpha: ${meta.hasAlpha})`);
console.log(`artwork    ${box.width}x${box.height} at ${box.left},${box.top} — ` +
  `${(100 - (box.width * box.height * 100) / (meta.width * meta.height)).toFixed(0)}% of the canvas was empty margin`);
for (const r of report) console.log(`wrote      ${r.out}  ${r.w}x${r.h}  ${r.kb} KB`);
console.log(`\nlazy-loaded and below the fold — a first visit pays none of this.`);
if (largest.w < 640) {
  console.log(`\nNOTE  the artwork caps at ${box.width}px, so it is sized in CSS to suit that and`);
  console.log(`      will be soft on a 2x screen at any larger size. A re-export at 1000px+`);
  console.log(`      needs no code change — drop it in, re-run, the extra widths appear.`);
}
