/**
 * Hero artwork pipeline: the client's render -> responsive full-bleed WebP.
 *
 *   node tools/hero.mjs [--check]
 *
 * The hero used to be a cutout — the surfer knocked out of a white ground and set
 * beside the copy as a monogram. The client replaced the artwork with a cinematic
 * landscape and asked for full bleed, so the keying is gone: there is no ground to
 * remove when the image IS the background. That version of this file, including the
 * border flood-fill and the alpha feathering, is in git at bb15c55 if the cutout
 * hero ever comes back.
 *
 * What matters now is weight. This image is the LCP element on every first visit and
 * it is photographic, busy, and 2.4 MB as delivered — so it ships at four widths and
 * the markup picks one, rather than every phone pulling a desktop-sized file.
 *
 * `src/data/hero-art.json` is written with the measured dimensions of each output.
 * The markup reads its srcset from there so a re-export at a different size cannot
 * leave the page advertising widths the files do not have.
 */

import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

/* Highest usable resolution first. hero.png at the repo root is where the client
   drops each new render; brand/ holds the previous ones so a re-run can never
   silently pick up something smaller than what is already shipped. */
const CANDIDATES = ['src/assets/hero-full.png', 'hero.png', 'brand/hero-full.png'];
const OUT = 'public/art';
const MANIFEST = 'src/data/hero-art.json';
const NAME = 'hero';

/* 640 covers phones at 2x, 1536 is the source's own width and the ceiling — there is
   no honest 2560 to give a desktop, and upscaling would only cost bytes. */
const WIDTHS = [640, 960, 1280, 1536];

/* Photographic and extremely busy: every quality point costs real kilobytes here.
   72 was chosen by measurement, not habit — see the printout. */
const QUALITY = 72;

const src = CANDIDATES.find((f) => existsSync(f));
if (!src) {
  console.error(`no source image found — looked for:\n  ${CANDIDATES.join('\n  ')}`);
  process.exit(1);
}

const meta = await sharp(src).metadata();
await mkdir(OUT, { recursive: true });

const report = [];
for (const width of WIDTHS) {
  if (width > meta.width) continue; // never upscale; the file would be bytes without detail
  const out = `${OUT}/${NAME}-${width}.webp`;
  const buf = await sharp(src)
    .resize({ width, withoutEnlargement: true })
    .webp({ quality: QUALITY, effort: 6 })
    .toBuffer();
  await writeFile(out, buf);
  const m = await sharp(buf).metadata();
  report.push({ out, w: m.width, h: m.height, kb: +(buf.length / 1024).toFixed(1) });
}

if (!report.length) {
  console.error(`source is ${meta.width}px wide — smaller than the narrowest output`);
  process.exit(1);
}

const largest = report.at(-1);

await mkdir('src/data', { recursive: true });
await writeFile(
  MANIFEST,
  JSON.stringify(
    {
      note: 'generated by tools/hero.mjs — do not edit by hand',
      /* The smallest file is the `src`. It is the fallback for anything that cannot
         read a srcset, and on those clients a soft hero beats a 300 KB one. */
      src: `/${report[0].out.replace(/^public\//, '')}`,
      width: largest.w,
      height: largest.h,
      ratio: +(largest.w / largest.h).toFixed(4),
      sources: report.map((r) => ({ src: `/${r.out.replace(/^public\//, '')}`, w: r.w })),
    },
    null,
    2,
  ) + '\n',
);

console.log(`source     ${src} (${meta.width}x${meta.height}, ${(meta.size / 1024 / 1024).toFixed(1)} MB)`);
for (const r of report) console.log(`wrote      ${r.out}  ${r.w}x${r.h}  ${r.kb} KB`);
console.log(`\nfirst visit pays whichever ONE of these the viewport picks, not the sum.`);

if (process.argv.includes('--check')) {
  /* The hero carries white type over the image, so what matters is not how the
     picture looks but how dark it is where the words go. This prints mean luminance
     for the band the centred copy occupies, before any scrim is applied. */
  const W = 1200;
  const probe = await sharp(src).resize({ width: W }).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  const { width: pw, height: ph } = probe.info;
  const band = (y0, y1, label) => {
    let sum = 0;
    let n = 0;
    for (let y = Math.floor(ph * y0); y < Math.floor(ph * y1); y++) {
      for (let x = 0; x < pw; x++) {
        const o = (y * pw + x) * 3;
        // Rec. 709 luma, good enough for "is this dark enough to carry white text"
        sum += 0.2126 * probe.data[o] + 0.7152 * probe.data[o + 1] + 0.0722 * probe.data[o + 2];
        n++;
      }
    }
    console.log(`  ${label.padEnd(26)} mean luma ${(sum / n).toFixed(1)}/255`);
  };
  console.log('\nunscrimmed luminance by band:');
  band(0.0, 0.22, 'top (nav)');
  band(0.3, 0.72, 'middle (headline)');
  band(0.72, 1.0, 'bottom (CTAs)');
}
