import { services } from './services';

/** The 7-step working process, in the order it runs each month. */
export const process = [
  {
    n: 1,
    title: 'Discovery Meeting',
    body: 'We sit down to understand your business, your goals, and exactly who you want to reach.',
  },
  {
    n: 2,
    title: 'Strategy Planning',
    body: 'A plan built for your brand and your market — not a template we ran for someone else last month.',
  },
  {
    n: 3,
    title: 'Content Creation',
    body: 'We write, shoot, design and schedule everything the plan asks for.',
  },
  {
    n: 4,
    title: 'Client Approval',
    body: 'You see everything before it goes live. Your feedback comes back in, and we make it right.',
  },
  {
    n: 5,
    title: 'Publishing',
    body: 'Posted on time, every time — and the comments and DMs get answered, not ignored.',
  },
  {
    n: 6,
    title: 'Performance Tracking',
    body: 'We watch what the numbers do and adjust while the campaign is still running, not after.',
  },
  {
    n: 7,
    title: 'Monthly Report',
    body: 'A clear report every month: what we did, what it earned you, and what we are changing next.',
  },
] as const;

/**
 * The About copy, transcribed from the client's brochure rather than written here —
 * it is his description of his own business and he has already approved it.
 */
export const about = {
  body: [
    "At Social Surfers, we don't just manage your social media — we build your digital presence, tell your brand story and drive real growth.",
    'From creative content to performance marketing, we provide 360° digital solutions that help your business stand out, engage more and convert better.',
  ],
} as const;

/**
 * The three points that sit beside the About copy in the brochure, under the
 * category line. Short by design: they are a summary of the seven services, not a
 * competing list of them.
 */
export const solutions = [
  { icon: 'target', text: 'Build your digital presence.' },
  { icon: 'bubble', text: 'Tell your brand story.' },
  { icon: 'chart', text: 'Drive real growth.' },
] as const;

/** Industries the agency already works in. */
export const industries = [
  'Real Estate',
  'Education',
  'Gym & Fitness',
  'Healthcare',
  'Fashion',
  'Restaurant',
  'Salon & Spa',
  'E-commerce',
  'Automobile',
  'Travel',
] as const;

/** Why choose us — 9 points, styled as a pre-session checklist. */
export const whyUs = [
  'Dedicated & passionate team',
  'Customized strategy for every brand',
  'High quality content & designs',
  'Latest tools & technologies',
  'Fast communication & support',
  'Monthly performance reports',
  'Transparent work & timely delivery',
  'Result-driven digital marketing',
  'End-to-end brand management',
] as const;

/** The four value pillars from the brochure. */
export const pillars = ['Strategy', 'Creativity', 'Technology', 'Results'] as const;

import clientData from './clients.json';

export interface Client {
  name: string;
  industry: string;
  /** tile under /public/clients, generated by tools/logos.mjs */
  logo: string;
}

/**
 * The client roster.
 *
 * Generated — do not hand-edit `clients.json`. It is written by `tools/logos.mjs`
 * from the raw artwork in `src/assets` plus the name map in `tools/clients.json`.
 * To add a client: drop the artwork in, add a line to the name map, re-run the tool.
 *
 * TODO(client): three names could not be read off the logo with confidence and are
 * flagged `verify` in tools/clients.json — Silomin, Looms in Velvet, and one that is
 * still a placeholder ("Client 27"). Confirm before launch.
 */
export const clients: readonly Client[] = clientData;

/**
 * Headline figures.
 *
 * DIRECTED BY THE CLIENT (2026-08-08): every figure doubled, and confirmed as his
 * call after the consequence was put to him.
 *
 * Three of the four used to be DERIVED from page content and are now decoupled from
 * it, so they no longer agree with what a visitor can count on the same page:
 *
 *   brands            54  — the logo wall renders 27 tiles
 *   industriesServed  20  — 10 are named in `industries` above
 *   serviceLines      14  — there are 7 cards and 7 service pages
 *
 * The first two are defensible because the roster and the industry list are framed
 * as partial ("a selection of", "including") — an agency plainly need not have a
 * logo for every client. The third has no such out: the number sits on the same
 * screen as a countable set of seven. It is the one worth revisiting with him.
 *
 * `projectsDelivered` is the only figure with no page-level contradiction — it is
 * his own count ("around 40–45"), doubled, and only he can confirm it.
 */
export const stats = {
  projectsDelivered: 80,
  brands: 54,
  industriesServed: 20,
  serviceLines: 14,
} as const;

/**
 * PLACEHOLDER — no real testimonials exist in the brochure.
 * Do NOT ship these. Either the client supplies real quotes with named businesses,
 * or the Proof section falls back to `clients` + service readouts only.
 * The section reads `hasRealTestimonials` and degrades on its own.
 */
export const hasRealTestimonials = false;

export const testimonials = [
  {
    client: 'Client Name',
    business: 'Business Name',
    industry: 'Industry',
    quote: 'Awaiting a real quote from the client — this block does not render while hasRealTestimonials is false.',
    result: '',
    date: '',
  },
] as const;
