import { services } from './services';

/** The 7-step working process, in the order it runs each month. */
export const process = [
  {
    n: 1,
    title: 'Discovery Meeting',
    body: 'We sit down to understand your business, your goals, and exactly who you want to reach.',
  },
  {
    n: 2,
    title: 'Strategy Planning',
    body: 'A plan built for your brand and your market — not a template we ran for someone else last month.',
  },
  {
    n: 3,
    title: 'Content Creation',
    body: 'We write, shoot, design and schedule everything the plan asks for.',
  },
  {
    n: 4,
    title: 'Client Approval',
    body: 'You see everything before it goes live. Your feedback comes back in, and we make it right.',
  },
  {
    n: 5,
    title: 'Publishing',
    body: 'Posted on time, every time — and the comments and DMs get answered, not ignored.',
  },
  {
    n: 6,
    title: 'Performance Tracking',
    body: 'We watch what the numbers do and adjust while the campaign is still running, not after.',
  },
  {
    n: 7,
    title: 'Monthly Report',
    body: 'A clear report every month: what we did, what it earned you, and what we are changing next.',
  },
] as const;

/** Industries the agency already works in. */
export const industries = [
  'Real Estate',
  'Education',
  'Gym & Fitness',
  'Healthcare',
  'Fashion',
  'Restaurant',
  'Salon & Spa',
  'E-commerce',
  'Automobile',
  'Travel',
] as const;

/** Why choose us — 9 points, styled as a pre-session checklist. */
export const whyUs = [
  'Dedicated & passionate team',
  'Customized strategy for every brand',
  'High quality content & designs',
  'Latest tools & technologies',
  'Fast communication & support',
  'Monthly performance reports',
  'Transparent work & timely delivery',
  'Result-driven digital marketing',
  'End-to-end brand management',
] as const;

/** The four value pillars from the brochure. */
export const pillars = ['Strategy', 'Creativity', 'Technology', 'Results'] as const;

import clientData from './clients.json';

export interface Client {
  name: string;
  industry: string;
  /** tile under /public/clients, generated by tools/logos.mjs */
  logo: string;
}

/**
 * The client roster.
 *
 * Generated — do not hand-edit `clients.json`. It is written by `tools/logos.mjs`
 * from the raw artwork in `src/assets` plus the name map in `tools/clients.json`.
 * To add a client: drop the artwork in, add a line to the name map, re-run the tool.
 *
 * TODO(client): three names could not be read off the logo with confidence and are
 * flagged `verify` in tools/clients.json — Silomin, Looms in Velvet, and one that is
 * still a placeholder ("Client 27"). Confirm before launch.
 */
export const clients: readonly Client[] = clientData;

/**
 * Headline figures.
 *
 * `projectsDelivered` is the client's own count, relayed through the account lead
 * as "around 40–45, a few more in the pipeline". Stated as the conservative floor
 * (40+) until he confirms an exact number — understating is recoverable, the
 * reverse is not. `brands` is not an estimate: it is the length of the roster.
 */
export const stats = {
  projectsDelivered: 40,
  brands: clients.length,
  industriesServed: industries.length,
  serviceLines: services.length,
} as const;

/**
 * PLACEHOLDER — no real testimonials exist in the brochure.
 * Do NOT ship these. Either the client supplies real quotes with named businesses,
 * or the Proof section falls back to `clients` + service readouts only.
 * The section reads `hasRealTestimonials` and degrades on its own.
 */
export const hasRealTestimonials = false;

export const testimonials = [
  {
    client: 'Client Name',
    business: 'Business Name',
    industry: 'Industry',
    quote: 'Awaiting a real quote from the client — this block does not render while hasRealTestimonials is false.',
    result: '',
    date: '',
  },
] as const;
